version: '3.1'

services:
  db:
    image: mysql:8.0  # Certifique-se de estar usando uma versão estável e suportada
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
