version: '3.1'

services:
  db:
    image: mysql
    command: --mysql_native_password=on
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: